/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { WeatherDatumService } from "../weatherDatum.service";
import { WeatherDatumCreateInput } from "./WeatherDatumCreateInput";
import { WeatherDatum } from "./WeatherDatum";
import { WeatherDatumFindManyArgs } from "./WeatherDatumFindManyArgs";
import { WeatherDatumWhereUniqueInput } from "./WeatherDatumWhereUniqueInput";
import { WeatherDatumUpdateInput } from "./WeatherDatumUpdateInput";

export class WeatherDatumControllerBase {
  constructor(protected readonly service: WeatherDatumService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: WeatherDatum })
  async createWeatherDatum(
    @common.Body() data: WeatherDatumCreateInput
  ): Promise<WeatherDatum> {
    return await this.service.createWeatherDatum({
      data: data,
      select: {
        createdAt: true,
        data: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [WeatherDatum] })
  @ApiNestedQuery(WeatherDatumFindManyArgs)
  async weatherData(@common.Req() request: Request): Promise<WeatherDatum[]> {
    const args = plainToClass(WeatherDatumFindManyArgs, request.query);
    return this.service.weatherData({
      ...args,
      select: {
        createdAt: true,
        data: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: WeatherDatum })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async weatherDatum(
    @common.Param() params: WeatherDatumWhereUniqueInput
  ): Promise<WeatherDatum | null> {
    const result = await this.service.weatherDatum({
      where: params,
      select: {
        createdAt: true,
        data: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: WeatherDatum })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateWeatherDatum(
    @common.Param() params: WeatherDatumWhereUniqueInput,
    @common.Body() data: WeatherDatumUpdateInput
  ): Promise<WeatherDatum | null> {
    try {
      return await this.service.updateWeatherDatum({
        where: params,
        data: data,
        select: {
          createdAt: true,
          data: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: WeatherDatum })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteWeatherDatum(
    @common.Param() params: WeatherDatumWhereUniqueInput
  ): Promise<WeatherDatum | null> {
    try {
      return await this.service.deleteWeatherDatum({
        where: params,
        select: {
          createdAt: true,
          data: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
